import Header from "@/components/my_components/Header";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import ConvexClientProvider from "./ConvexClientProvider";

import { UserProvider } from "./userContext";

export const metadata = {
  title: "BluePrint",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <UserProvider>
          <ConvexClientProvider>
            <GoogleOAuthProvider
              clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}
            >
              <Header />
              {children}
            </GoogleOAuthProvider>
          </ConvexClientProvider>
        </UserProvider>
      </body>
    </html>
  );
}
